# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import echo_pb2 as echo__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in echo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EchoServiceStub:
    """EchoService provides test RPCs covering unary, streaming, auth, and schema change scenarios.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Echo = channel.unary_unary(
                '/grpc_test.EchoService/Echo',
                request_serializer=echo__pb2.EchoRequest.SerializeToString,
                response_deserializer=echo__pb2.EchoResponse.FromString,
                _registered_method=True)
        self.EchoStream = channel.unary_stream(
                '/grpc_test.EchoService/EchoStream',
                request_serializer=echo__pb2.EchoRequest.SerializeToString,
                response_deserializer=echo__pb2.EchoResponse.FromString,
                _registered_method=True)
        self.EchoWithMetadata = channel.unary_unary(
                '/grpc_test.EchoService/EchoWithMetadata',
                request_serializer=echo__pb2.EchoRequest.SerializeToString,
                response_deserializer=echo__pb2.EchoResponse.FromString,
                _registered_method=True)
        self.EchoSlow = channel.unary_unary(
                '/grpc_test.EchoService/EchoSlow',
                request_serializer=echo__pb2.EchoRequest.SerializeToString,
                response_deserializer=echo__pb2.EchoResponse.FromString,
                _registered_method=True)
        self.EchoV1 = channel.unary_unary(
                '/grpc_test.EchoService/EchoV1',
                request_serializer=echo__pb2.EchoV1Request.SerializeToString,
                response_deserializer=echo__pb2.EchoV1Response.FromString,
                _registered_method=True)
        self.EchoV2 = channel.unary_unary(
                '/grpc_test.EchoService/EchoV2',
                request_serializer=echo__pb2.EchoV2Request.SerializeToString,
                response_deserializer=echo__pb2.EchoV2Response.FromString,
                _registered_method=True)
        self.EchoSlowStream = channel.unary_stream(
                '/grpc_test.EchoService/EchoSlowStream',
                request_serializer=echo__pb2.EchoRequest.SerializeToString,
                response_deserializer=echo__pb2.EchoResponse.FromString,
                _registered_method=True)
        self.EchoClientStream = channel.stream_unary(
                '/grpc_test.EchoService/EchoClientStream',
                request_serializer=echo__pb2.EchoRequest.SerializeToString,
                response_deserializer=echo__pb2.EchoResponse.FromString,
                _registered_method=True)
        self.EchoBidiStream = channel.stream_stream(
                '/grpc_test.EchoService/EchoBidiStream',
                request_serializer=echo__pb2.EchoRequest.SerializeToString,
                response_deserializer=echo__pb2.EchoResponse.FromString,
                _registered_method=True)
        self.EchoLarge = channel.unary_unary(
                '/grpc_test.EchoService/EchoLarge',
                request_serializer=echo__pb2.LargePayload.SerializeToString,
                response_deserializer=echo__pb2.LargePayload.FromString,
                _registered_method=True)


class EchoServiceServicer:
    """EchoService provides test RPCs covering unary, streaming, auth, and schema change scenarios.
    """

    def Echo(self, request, context):
        """Basic unary echo.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoStream(self, request, context):
        """Server-streaming echo: returns 5 chunks with incrementing sequence numbers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoWithMetadata(self, request, context):
        """Metadata-authenticated echo: requires "authorization: Bearer test-token".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoSlow(self, request, context):
        """Slow echo: 3-second delay for deadline/timeout testing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoV1(self, request, context):
        """Schema v1: 2-field request for schema migration testing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoV2(self, request, context):
        """Schema v2: adds priority field for schema change diff testing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoSlowStream(self, request, context):
        """Slow server stream: 5 chunks at 1s intervals, for cancellation testing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoClientStream(self, request_iterator, context):
        """Client-streaming echo: concatenates every request chunk into one response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoBidiStream(self, request_iterator, context):
        """Bidirectional echo: echoes each request chunk back as it arrives.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EchoLarge(self, request, context):
        """Large payload echo for big message testing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EchoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Echo': grpc.unary_unary_rpc_method_handler(
                    servicer.Echo,
                    request_deserializer=echo__pb2.EchoRequest.FromString,
                    response_serializer=echo__pb2.EchoResponse.SerializeToString,
            ),
            'EchoStream': grpc.unary_stream_rpc_method_handler(
                    servicer.EchoStream,
                    request_deserializer=echo__pb2.EchoRequest.FromString,
                    response_serializer=echo__pb2.EchoResponse.SerializeToString,
            ),
            'EchoWithMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.EchoWithMetadata,
                    request_deserializer=echo__pb2.EchoRequest.FromString,
                    response_serializer=echo__pb2.EchoResponse.SerializeToString,
            ),
            'EchoSlow': grpc.unary_unary_rpc_method_handler(
                    servicer.EchoSlow,
                    request_deserializer=echo__pb2.EchoRequest.FromString,
                    response_serializer=echo__pb2.EchoResponse.SerializeToString,
            ),
            'EchoV1': grpc.unary_unary_rpc_method_handler(
                    servicer.EchoV1,
                    request_deserializer=echo__pb2.EchoV1Request.FromString,
                    response_serializer=echo__pb2.EchoV1Response.SerializeToString,
            ),
            'EchoV2': grpc.unary_unary_rpc_method_handler(
                    servicer.EchoV2,
                    request_deserializer=echo__pb2.EchoV2Request.FromString,
                    response_serializer=echo__pb2.EchoV2Response.SerializeToString,
            ),
            'EchoSlowStream': grpc.unary_stream_rpc_method_handler(
                    servicer.EchoSlowStream,
                    request_deserializer=echo__pb2.EchoRequest.FromString,
                    response_serializer=echo__pb2.EchoResponse.SerializeToString,
            ),
            'EchoClientStream': grpc.stream_unary_rpc_method_handler(
                    servicer.EchoClientStream,
                    request_deserializer=echo__pb2.EchoRequest.FromString,
                    response_serializer=echo__pb2.EchoResponse.SerializeToString,
            ),
            'EchoBidiStream': grpc.stream_stream_rpc_method_handler(
                    servicer.EchoBidiStream,
                    request_deserializer=echo__pb2.EchoRequest.FromString,
                    response_serializer=echo__pb2.EchoResponse.SerializeToString,
            ),
            'EchoLarge': grpc.unary_unary_rpc_method_handler(
                    servicer.EchoLarge,
                    request_deserializer=echo__pb2.LargePayload.FromString,
                    response_serializer=echo__pb2.LargePayload.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_test.EchoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('grpc_test.EchoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EchoService:
    """EchoService provides test RPCs covering unary, streaming, auth, and schema change scenarios.
    """

    @staticmethod
    def Echo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_test.EchoService/Echo',
            echo__pb2.EchoRequest.SerializeToString,
            echo__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EchoStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grpc_test.EchoService/EchoStream',
            echo__pb2.EchoRequest.SerializeToString,
            echo__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EchoWithMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_test.EchoService/EchoWithMetadata',
            echo__pb2.EchoRequest.SerializeToString,
            echo__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EchoSlow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_test.EchoService/EchoSlow',
            echo__pb2.EchoRequest.SerializeToString,
            echo__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EchoV1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_test.EchoService/EchoV1',
            echo__pb2.EchoV1Request.SerializeToString,
            echo__pb2.EchoV1Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EchoV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_test.EchoService/EchoV2',
            echo__pb2.EchoV2Request.SerializeToString,
            echo__pb2.EchoV2Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EchoSlowStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/grpc_test.EchoService/EchoSlowStream',
            echo__pb2.EchoRequest.SerializeToString,
            echo__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EchoClientStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/grpc_test.EchoService/EchoClientStream',
            echo__pb2.EchoRequest.SerializeToString,
            echo__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EchoBidiStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/grpc_test.EchoService/EchoBidiStream',
            echo__pb2.EchoRequest.SerializeToString,
            echo__pb2.EchoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EchoLarge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/grpc_test.EchoService/EchoLarge',
            echo__pb2.LargePayload.SerializeToString,
            echo__pb2.LargePayload.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
