# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: echo.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'echo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\tgrpc_test\"-\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\"A\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\x12\x11\n\tserver_id\x18\x03 \x01(\t\",\n\rEchoV1Request\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\"=\n\x0e\x45\x63hoV1Response\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\x12\x0e\n\x06result\x18\x03 \x01(\t\">\n\rEchoV2Request\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\x12\x10\n\x08priority\x18\x03 \x01(\x05\"O\n\x0e\x45\x63hoV2Response\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\x12\x10\n\x08priority\x18\x03 \x01(\x05\x12\x0e\n\x06result\x18\x04 \x01(\t\":\n\x0cLargePayload\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x0e\n\x06marker\x18\x03 \x01(\t2\x99\x05\n\x0b\x45\x63hoService\x12\x37\n\x04\x45\x63ho\x12\x16.grpc_test.EchoRequest\x1a\x17.grpc_test.EchoResponse\x12?\n\nEchoStream\x12\x16.grpc_test.EchoRequest\x1a\x17.grpc_test.EchoResponse0\x01\x12\x43\n\x10\x45\x63hoWithMetadata\x12\x16.grpc_test.EchoRequest\x1a\x17.grpc_test.EchoResponse\x12;\n\x08\x45\x63hoSlow\x12\x16.grpc_test.EchoRequest\x1a\x17.grpc_test.EchoResponse\x12=\n\x06\x45\x63hoV1\x12\x18.grpc_test.EchoV1Request\x1a\x19.grpc_test.EchoV1Response\x12=\n\x06\x45\x63hoV2\x12\x18.grpc_test.EchoV2Request\x1a\x19.grpc_test.EchoV2Response\x12\x43\n\x0e\x45\x63hoSlowStream\x12\x16.grpc_test.EchoRequest\x1a\x17.grpc_test.EchoResponse0\x01\x12\x45\n\x10\x45\x63hoClientStream\x12\x16.grpc_test.EchoRequest\x1a\x17.grpc_test.EchoResponse(\x01\x12\x45\n\x0e\x45\x63hoBidiStream\x12\x16.grpc_test.EchoRequest\x1a\x17.grpc_test.EchoResponse(\x01\x30\x01\x12=\n\tEchoLarge\x12\x17.grpc_test.LargePayload\x1a\x17.grpc_test.LargePayloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECHOREQUEST']._serialized_start=25
  _globals['_ECHOREQUEST']._serialized_end=70
  _globals['_ECHORESPONSE']._serialized_start=72
  _globals['_ECHORESPONSE']._serialized_end=137
  _globals['_ECHOV1REQUEST']._serialized_start=139
  _globals['_ECHOV1REQUEST']._serialized_end=183
  _globals['_ECHOV1RESPONSE']._serialized_start=185
  _globals['_ECHOV1RESPONSE']._serialized_end=246
  _globals['_ECHOV2REQUEST']._serialized_start=248
  _globals['_ECHOV2REQUEST']._serialized_end=310
  _globals['_ECHOV2RESPONSE']._serialized_start=312
  _globals['_ECHOV2RESPONSE']._serialized_end=391
  _globals['_LARGEPAYLOAD']._serialized_start=393
  _globals['_LARGEPAYLOAD']._serialized_end=451
  _globals['_ECHOSERVICE']._serialized_start=454
  _globals['_ECHOSERVICE']._serialized_end=1119
# @@protoc_insertion_point(module_scope)
